### ISSUE TITLE
Site config edits

### ISSUE THREAD

**Issue by parsiya** [parsiya/parsiya.fa#1]
The sidebar menu is used in the other modes of the papermod theme. I do not need them here. Unless I decide to change .

```yml
menu:
  sidebar:
    - name: Link 1
      url: 'https://example.com'
    - name: Link 2
      url: 'https://example.org'
```

Remove the post pictures in the index, Supposedly these will do it. But I remember changing it would mess up the front page or something. Those pictures take a lot of real estate.

```yml
  cover:
    # hiddenInList: true # uncomment to disable the post cover image in the index
    # hiddenInSingle: true
```
